### ISSUE TITLE
plot_DGs unusual result

### ISSUE THREAD

**Issue by callumjd** [openforcefield/Arsenic#24]
Using the provided example.csv data, I cannot reproduce the DGs plot - the experimental data seems to be the negative of the true value.

Please let me know if I've done something wrong - PDF of notebook attached. Everything else looks correct.

[absolute_wrong.pdf](https://github.com/openforcefield/Arsenic/files/5330188/absolute_wrong.pdf)

**Comment by hannahbrucemacdonald** [comment]
Hmmm I’ve recently made a change in sign to try keep things consistent, but I might not have tested it with all plot types so this looks like a bug. I will look into it and write a test so that it doesn’t happen again.


Sorry I’m still trying to figure out the right API so the package is still very much WIP!

**Comment by callumjd** [comment]
Does seem like a sign issue - totally understand that it is WIP. Very nice for FEP analysis though, happy to be a beta tester!

**Comment by hannahbrucemacdonald** [comment]
Ok

`import networkx as nx
g = nx.DiGraph()

for i,j in enumerate([-10,-9,-8]): 
    g.add_node(i, exp_DG=j, calc_DG=j,exp_dDG=0.2, calc_dDG=0.2)
    
plotting.plot_DGs(g)`


gives:
![image](https://user-images.githubusercontent.com/43652597/95682845-a2b02f00-0bdf-11eb-8c85-57def69caa52.png)


so it's not in the `plot_DGs` function... must be before that

**Comment by hannahbrucemacdonald** [comment]
This should be fixed in master now! Sorry for slowness and thanks for flagging the mistake!

**Comment by callumjd** [comment]
> This should be fixed in master now! Sorry for slowness and thanks for flagging the mistake!

Thanks! Have just tested, looks good 👍
